C17 = g++ --std=c++17

all:
	$(C17) -o reverse.o reverse.cpp
	@echo
	@echo './reverse.o [args] to run'

reverse:
	$(C17) -o reverse.o reverse.cpp
	@echo
	@echo './reverse.o [args] to run'
clean:
	rm -f ./*.o
	@rm -f ./reverse
	@rm -f ./a.out
